
import Connect.DBCon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class InsertionForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form InsertionForm
     */
    public InsertionForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        quelabel = new javax.swing.JLabel();
        option1label = new javax.swing.JLabel();
        option1tf = new javax.swing.JTextField();
        option4label = new javax.swing.JLabel();
        option7tf = new javax.swing.JTextField();
        option2tf = new javax.swing.JTextField();
        option2label = new javax.swing.JLabel();
        option3tf = new javax.swing.JTextField();
        option3label = new javax.swing.JLabel();
        option4tf = new javax.swing.JTextField();
        correctanslabel = new javax.swing.JLabel();
        correctanstf = new javax.swing.JTextField();
        SNolabel = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        panel3 = new java.awt.Panel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(980, 950));

        panel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Insert Ques");
        panel1.add(jLabel1);

        getContentPane().add(panel1, java.awt.BorderLayout.NORTH);

        panel2.setBackground(new java.awt.Color(204, 255, 255));

        quelabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        quelabel.setText("Question");

        option1label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        option1label.setText("Option 1");

        option1tf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        option1tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1tfActionPerformed(evt);
            }
        });

        option4label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        option4label.setText("Option 4");

        option7tf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        option2tf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        option2tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2tfActionPerformed(evt);
            }
        });

        option2label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        option2label.setText("Option 2");

        option3tf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        option3tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3tfActionPerformed(evt);
            }
        });

        option3label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        option3label.setText("Option 3");

        option4tf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        correctanslabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        correctanslabel.setText("Correct Answer");

        correctanstf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        SNolabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SNolabel.setText("S_No");

        textArea1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SNolabel)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(option1label)
                            .addComponent(quelabel)
                            .addComponent(option2label)
                            .addComponent(option3label)
                            .addComponent(option4label)
                            .addComponent(correctanslabel))
                        .addGap(38, 38, 38)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(correctanstf)
                            .addComponent(option2tf)
                            .addComponent(option3tf)
                            .addComponent(option4tf)
                            .addComponent(option1tf)
                            .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                            .addComponent(option7tf))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SNolabel)
                    .addComponent(option7tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(quelabel))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option2tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option1label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option3tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option2label))
                .addGap(29, 29, 29)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option4tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option3label))
                .addGap(27, 27, 27)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option1tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option4label))
                .addGap(23, 23, 23)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correctanslabel)
                    .addComponent(correctanstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        getContentPane().add(panel2, java.awt.BorderLayout.CENTER);

        panel3.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButton2)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(panel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void option1tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option1tfActionPerformed

    private void option3tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option3tfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String query="insert into questions(S_No,Que,optiona,optionb,optionc,optiond,correctans) values('"+option7tf.getText()+"','"+textArea1.getText()+"','"+option2tf.getText()+"','"+option3tf.getText()+"','"+option4tf.getText()+"','"+option1tf.getText()+"','"+correctanstf.getText()+"')";
        DBCon con=new DBCon();
        con.insertData(query);
        JOptionPane.showMessageDialog(null, "Inserted Success");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        textArea1.setText("");
        option2tf.setText("");
        option3tf.setText("");
        option4tf.setText("");
        option1tf.setText("");
        correctanstf.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void option2tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option2tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SNolabel;
    private javax.swing.JLabel correctanslabel;
    private javax.swing.JTextField correctanstf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel option1label;
    private javax.swing.JTextField option1tf;
    private javax.swing.JLabel option2label;
    private javax.swing.JTextField option2tf;
    private javax.swing.JLabel option3label;
    private javax.swing.JTextField option3tf;
    private javax.swing.JLabel option4label;
    private javax.swing.JTextField option4tf;
    private javax.swing.JTextField option7tf;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private javax.swing.JLabel quelabel;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
